blank_issues_enabled: false
contact_links:
  - name: VerbaManent GitHub Discussions
    url: https://github.com/giordebug/verbamanent/discussions
    about: Please ask and answer questions here.
  - name: VerbaManent issue disclosure
    about: Please report security vulnerabilities here.
